### ISSUE TITLE
Projet QGIS : Modifier l'apparence par défaut de l'objet identifié

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/ocs2d#5]
### Retour CoTech 22/06/2022

Le contour rouge + fond rouge semi-transparent gêne à la bonne visibilité de l'objet à interpréter.
L'option est disponible dans QGIS dans les préférences globales et non dans le projet.

Voir s'il est possible de le forcer dans le projet modèle.
Sinon mettre à jour le guide technique QGIS en conséquence pour indiquer où faire la modification

**Comment by Doctor-Who** [comment]
Piste sur le chat QGIS-fr :

> dans une macro à l'ouverture du projet qs.setValue("Map/highlight/color", "#ff00ff") avec qs = QgsSettings() et la remettre à la valeur par défaut à la fermeture du projet ?

**Comment by jbdesbas** [comment]
La couleur "objet identifé" ne peut pas être modifiée au niveau du projet (à l'inverse de la couleur "sélection"), mais les macros permettent effectivement de surcoucher les paramètres de QGIS lors du lancement d'un projet (et de remettre la valeur par défaut à la fermeture).
Par contre l'utilisateur reçoit un avertissement lui demandant d'autoriser les macro.

Dans `projet -> propriétés -> macro`

```python
from qgis.core import QgsSettings

settings=QgsSettings()

def openProject():
    new_color="#0000ff"  # A adapter 
    settings.setValue("Map/highlight/color", new_color)

def saveProject():
    pass

def closeProject():
    settings.setValue("Map/highlight/color", None)
```
